//! The synthetic files the desktop smoke test feeds to the app. They are generated by the
//! builder; set KALBION_UPDATE_FIXTURES=1 to rewrite them after changing it.
mod common;
use common::*;

fn smoke_capture() -> Vec<u8> {
    pcap(&[
        (
            T0 + 1,
            0,
            from_server(&packet(&[reliable(1, &loot("Mob", "Kazz", 950, 30))])),
        ),
        (
            T0 + 2,
            0,
            from_server(&packet(&[reliable(2, &loot("Baú", "Luna", 2888, 1))])),
        ),
        (
            T0 + 3,
            0,
            from_server(&packet(&[reliable(3, &loot("Mob", "Thorin", 1088, 12))])),
        ),
        // Not on any roster the smoke test uses.
        (
            T0 + 4,
            0,
            from_server(&packet(&[reliable(4, &loot("Kazz", "Inimigo", 4100, 1))])),
        ),
        // Not in the catalog.
        (
            T0 + 5,
            0,
            from_server(&packet(&[reliable(5, &loot("Mob", "Kazz", 99999, 2))])),
        ),
        (
            T0 + 6,
            0,
            from_server(&packet(&[reliable(6, &silver("Kazz"))])),
        ),
        (
            T0 + 7,
            0,
            from_server(&packet(&[reliable(7, &other_event(123))])),
        ),
    ])
}

fn check(name: &str, contents: &[u8]) {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    if std::env::var_os("KALBION_UPDATE_FIXTURES").is_some() {
        std::fs::write(&path, contents).unwrap();
    }
    assert_eq!(
        std::fs::read(&path).unwrap(),
        contents,
        "{name} is out of date; run with KALBION_UPDATE_FIXTURES=1"
    );
}

#[test]
fn committed_fixtures_match_the_builder() {
    check("synthetic-loot.pcap", &smoke_capture());
    check("synthetic-items.json", catalog_json().as_bytes());
    let capture =
        kalbion_capture::decode(&smoke_capture()[..], kalbion_capture::Limits::default()).unwrap();
    assert_eq!(capture.observations.len(), 5);
    assert_eq!(capture.diagnostics.loot_silver, 1);
}
